version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "redeliverlambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15dl5gj2z66t4"
s3_prefix = "redeliverlambda"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
