AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  redeliverlambda

  Sample SAM Template for redeliverlambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  RedeliverFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: RedeliverFunction
      Handler: com.fmr.ecs.redeliver.RedeliverService::redeliver
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: 
        Variables:
          PARAM1: VALUE1234
      Events:
        Redeliver:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /redeliver
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RedeliverdApi:
    Description: "API Gateway endpoint URL for Prod stage for Redeliver function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/redeliver/"
  RedeliverFunction:
    Description: "Redeliver Lambda Function ARN"
    Value: !GetAtt RedeliverFunction.Arn
  RedeliverFunctionIamRole:
    Description: "Implicit IAM Role created for Redeliver function"
    Value: !GetAtt RedeliverFunctionRole.Arn
